name: responsive_navigation_bar_example
description: Demonstrates how to use the responsive_navigation_bar plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0'

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  responsive_navigation_bar:
    path: ../


dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
