name: responsive_navigation_bar
description: A responsive bottom navigation bar. Very beginner friendly. Feel free to contribute.
version: 2.0.3
homepage: https://github.com/nohli/navigation_bar

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.2

flutter:
  plugin:
    platforms:
      android:
        package: com.achimsapps.responsive_navigation_bar
        pluginClass: ResponsiveNavigationBarPlugin
      ios:
        pluginClass: ResponsiveNavigationBarPlugin
      macos:
        pluginClass: ResponsiveNavigationBarPlugin
      windows:
        pluginClass: ResponsiveNavigationBarPlugin
      linux:
        pluginClass: ResponsiveNavigationBarPlugin
      web:
        fileName: responsive_navigation_bar_web.dart
        pluginClass: ResponsiveNavigationBarWeb
