name: responsive_navigation_bar
description: A responsive bottom navigation bar. Very beginner friendly. Feel free to contribute.
homepage: https://github.com/nohli/responsive_navigation_bar

version: 3.1.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
