name: responsive_navigation_bar
description: A responsive bottom navigation bar. Very beginner friendly. Feel free to contribute.
version: 0.1.6
homepage: https://github.com/nohli/navigation_bar

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.achimsapps.responsive_navigation_bar
        pluginClass: ResponsiveNavigationBarPlugin
      ios:
        pluginClass: ResponsiveNavigationBarPlugin
      macos:
        pluginClass: ResponsiveNavigationBarPlugin
      web:
        fileName: responsive_navigation_bar_web.dart
        pluginClass: ResponsiveNavigationBarWeb
