name: responsive_navigation_bar
description: A responsive (and floatable) bottom navigation bar. Very beginner friendly.
version: 0.0.3
homepage: https://github.com/nohli/navigation_bar

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.20.1 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.achimsapps.responsive_navigation_bar
        pluginClass: ResponsiveNavigationBarPlugin
      ios:
        pluginClass: ResponsiveNavigationBarPlugin